[2024-03-29T00:31:06.691+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-03-29T00:31:06.705+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2024-03-29T00:31:06.706+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 6
[2024-03-29T00:31:06.727+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sptoify_to_csv> on 2024-03-28 00:00:00+00:00
[2024-03-29T00:31:06.736+0000] {standard_task_runner.py:60} INFO - Started process 1666 to run task
[2024-03-29T00:31:06.741+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'billboard_to_spotify_to_s3_extractionV1', 'sptoify_to_csv', 'scheduled__2024-03-28T00:00:00+00:00', '--job-id', '1491', '--raw', '--subdir', 'DAGS_FOLDER/billboard_to_spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpu_z988oj']
[2024-03-29T00:31:06.745+0000] {standard_task_runner.py:88} INFO - Job 1491: Subtask sptoify_to_csv
[2024-03-29T00:31:06.819+0000] {task_command.py:423} INFO - Running <TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-03-28T00:00:00+00:00 [running]> on host bc244bd8b198
[2024-03-29T00:31:06.941+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='billboard_to_spotify_to_s3_extractionV1' AIRFLOW_CTX_TASK_ID='sptoify_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T00:00:00+00:00'
[2024-03-29T00:31:06.961+0000] {logging_mixin.py:188} INFO - GOT THE TOP ARTISTS DAT FROM XCOM
[2024-03-29T00:31:06.963+0000] {logging_mixin.py:188} INFO - GETTING ARTISTS BIO DATA
[2024-03-29T00:31:07.583+0000] {logging_mixin.py:188} INFO - GETTING ARTISTS ALBUMS DATA
[2024-03-29T00:31:07.984+0000] {logging_mixin.py:188} INFO - Taylor Swift has appeared on a total of 385 albums
[2024-03-29T00:31:07.985+0000] {logging_mixin.py:188} INFO -  Now stagging the albums ...
[2024-03-29T00:31:15.632+0000] {logging_mixin.py:188} INFO -  Taylor Swift albums stagged ... 
[2024-03-29T00:31:15.633+0000] {logging_mixin.py:188} INFO -  transforming Taylor Swift albums data ... 
[2024-03-29T00:31:15.634+0000] {logging_mixin.py:188} INFO - GETTING ALBUMS TRACKS DATA
[2024-03-29T00:31:15.863+0000] {logging_mixin.py:188} INFO -  Now stagging the tracks ...
[2024-03-29T00:31:15.864+0000] {logging_mixin.py:188} INFO -  1989 (Taylor's Version) [Deluxe] tracks stagged ... 
[2024-03-29T00:31:15.865+0000] {logging_mixin.py:188} INFO -  transforming 1989 (Taylor's Version) [Deluxe] tracks data ... 
[2024-03-29T00:31:15.866+0000] {logging_mixin.py:188} INFO - i am here
[2024-03-29T00:31:18.266+0000] {client.py:302} ERROR - Max Retries reached
[2024-03-29T00:31:18.267+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 884, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/audio-features/?ids=4WUepByoeqcedHoYhSNHRt (Caused by ResponseError('too many 429 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 266, in _internal_call
    response = self._session.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/audio-features/?ids=4WUepByoeqcedHoYhSNHRt (Caused by ResponseError('too many 429 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/billboard_to_spotify_to_csvs_to_s3.py", line 156, in Spotify_to_CSV
    track_features = sp.audio_features(track['uri'])
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 1734, in audio_features
    results = self._get("audio-features/?ids=" + trackid)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 307, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 429, code:-1 - /v1/audio-features/?ids=4WUepByoeqcedHoYhSNHRt:
 Max Retries, reason: too many 429 error responses
[2024-03-29T00:31:18.285+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=billboard_to_spotify_to_s3_extractionV1, task_id=sptoify_to_csv, execution_date=20240328T000000, start_date=20240329T003106, end_date=20240329T003118
[2024-03-29T00:31:18.303+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1491 for task sptoify_to_csv (http status: 429, code:-1 - /v1/audio-features/?ids=4WUepByoeqcedHoYhSNHRt:
 Max Retries, reason: too many 429 error responses; 1666)
[2024-03-29T00:31:18.329+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-29T00:31:18.358+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
